language: python
python:
  - "3.7"
cache: pip
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10-postgis-2.5
services:
  - postgresql
before_install:
  - sudo apt-get install -y sqlite3
  - sudo apt install -y libgdal-dev libproj-dev libproj-dev
  - sudo apt install -y libsqlite3-dev spatialite-bin libsqlite3-mod-spatialite
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install codecov
script:
  - coverage3 run -m pytest tests
  - black --check --diff importers pepys_import pepys_admin
  - isort --check-only --diff importers pepys_import pepys_admin
after_success:
  - coverage3 report
  # Push the results back to codecov
  - codecov
