language: python
python:
  - "3.8"
cache: pip
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10-postgis-2.5
services:
  - postgresql
before_install:
  - sudo apt-get install -y sqlite3
  - sudo apt install -y libgdal-dev libproj-dev libproj-dev
  - sudo apt install -y libsqlite3-dev spatialite-bin libsqlite3-mod-spatialite
install:
  - pip install -r requirements.txt
  - pip install codecov
before_script:
  - sudo -u postgres psql -c "CREATE ROLE gis PASSWORD 'gis' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;"
  - sudo -u postgres createdb -E UTF-8 gis
  - sudo -u postgres psql -d test -c 'CREATE SCHEMA gis;'
  - sudo -u postgres psql -c 'GRANT CREATE ON DATABASE test TO "gis";'
  - sudo -u postgres psql -d test -c 'GRANT USAGE,CREATE ON SCHEMA gis TO "gis";'
  - sudo -u postgres psql -d test -U postgres -c "CREATE EXTENSION postgis;"
script:
  - coverage3 run -m unittest discover -v
  - black --check --diff pepys_import
after_success:
  - coverage3 report
  # Push the results back to codecov
  - codecov
