[tool.black]
line-length = 100
target-version = ['py37']

[tool.isort]
multi_line_output = 3  # Vertical Hanging Indent, which is supported by Black
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 100