from pprint import pprint

from pepys_admin.maintenance.column_data import convert_column_data_to_edit_data, create_column_data
from pepys_import.core.store.data_store import DataStore
from pepys_import.core.store.db_status import TableTypes


def test_column_data_platform():
    store = DataStore("", "", "", 0, ":memory:", db_type="sqlite")
    store.initialise()
    with store.session_scope():
        store.populate_reference()
        store.populate_metadata()

    col_data = create_column_data(store, store.db_classes.Platform)

    correct_col_data = {
        "created date": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "created_date",
            "type": "datetime",
        },
        "identifier": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "identifier",
            "type": "string",
            "values": ["A643", "A816", "C045", "P543"],
        },
        "name": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "name",
            "type": "string",
            "values": ["ADRI", "JEAN", "NARV", "SPAR"],
        },
        "nationality": {
            "foreign_table_type": TableTypes.REFERENCE,
            "multiple_values_allowed": False,
            "required": True,
            "second_level": False,
            "sqlalchemy_type": "relationship",
            "system_name": "nationality",
            "type": "string",
            "values": [
                "United Kingdom",
                "Canada",
                "France",
                "Germany",
                "Italy",
                "Netherlands",
                "United States",
                "Afghanistan",
                "Albania",
                "Algeria",
                "American Samoa",
                "Andorra",
                "Angola",
                "Anguilla",
                "Antarctica",
                "Antigua and Barbuda",
                "Argentina",
                "Armenia",
                "Aruba",
                "Australia",
                "Austria",
                "Azerbaijan",
                "Bahamas",
                "Bahrain",
                "Bangladesh",
                "Barbados",
                "Belarus",
                "Belgium",
                "Belize",
                "Benin",
                "Bermuda",
                "Bhutan",
                "Bolivia, Plurinational State of",
                "Bolivia",
                "Bosnia and Herzegovina",
                "Botswana",
                "Bouvet Island",
                "Brazil",
                "British Indian Ocean Territory",
                "Brunei Darussalam",
                "Brunei",
                "Bulgaria",
                "Burkina Faso",
                "Burundi",
                "Cambodia",
                "Cameroon",
                "Cape Verde",
                "Cayman Islands",
                "Central African Republic",
                "Chad",
                "Chile",
                "China",
                "Christmas Island",
                "Cocos (Keeling) Islands",
                "Colombia",
                "Comoros",
                "Congo",
                "Congo, the Democratic Republic of the",
                "Cook Islands",
                "Costa Rica",
                "Cote d'Ivoire",
                "Ivory Coast",
                "Croatia",
                "Cuba",
                "Cyprus",
                "Czech Republic",
                "Denmark",
                "Djibouti",
                "Dominica",
                "Dominican Republic",
                "Ecuador",
                "Egypt",
                "El Salvador",
                "Equatorial Guinea",
                "Eritrea",
                "Estonia",
                "Ethiopia",
                "Falkland Islands (Malvinas)",
                "Faroe Islands",
                "Fiji",
                "Finland",
                "French Guiana",
                "French Polynesia",
                "French Southern Territories",
                "Gabon",
                "Gambia",
                "Georgia",
                "Ghana",
                "Gibraltar",
                "Greece",
                "Greenland",
                "Grenada",
                "Guadeloupe",
                "Guam",
                "Guatemala",
                "Guernsey",
                "Guinea",
                "Guinea-Bissau",
                "Guyana",
                "Haiti",
                "Heard Island and McDonald Islands",
                "Holy See (Vatican City State)",
                "Honduras",
                "Hong Kong",
                "Hungary",
                "Iceland",
                "India",
                "Indonesia",
                "Iran, Islamic Republic of",
                "Iraq",
                "Ireland",
                "Isle of Man",
                "Israel",
                "Jamaica",
                "Japan",
                "Jersey",
                "Jordan",
                "Kazakhstan",
                "Kenya",
                "Kiribati",
                "Korea, Democratic People's Republic of",
                "Korea, Republic of",
                "South Korea",
                "Kuwait",
                "Kyrgyzstan",
                "Lao People's Democratic Republic",
                "Latvia",
                "Lebanon",
                "Lesotho",
                "Liberia",
                "Libyan Arab Jamahiriya",
                "Libya",
                "Liechtenstein",
                "Lithuania",
                "Luxembourg",
                "Macao",
                "Macedonia, the former Yugoslav Republic of",
                "Madagascar",
                "Malawi",
                "Malaysia",
                "Maldives",
                "Mali",
                "Malta",
                "Marshall Islands",
                "Martinique",
                "Mauritania",
                "Mauritius",
                "Mayotte",
                "Mexico",
                "Micronesia, Federated States of",
                "Moldova, Republic of",
                "Monaco",
                "Mongolia",
                "Montenegro",
                "Montserrat",
                "Morocco",
                "Mozambique",
                "Myanmar",
                "Burma",
                "Namibia",
                "Nauru",
                "Nepal",
                "Netherlands Antilles",
                "New Caledonia",
                "New Zealand",
                "Nicaragua",
                "Niger",
                "Nigeria",
                "Niue",
                "Norfolk Island",
                "Northern Mariana Islands",
                "Norway",
                "Oman",
                "Pakistan",
                "Palau",
                "Palestinian Territory, Occupied",
                "Panama",
                "Papua New Guinea",
                "Paraguay",
                "Peru",
                "Philippines",
                "Pitcairn",
                "Poland",
                "Portugal",
                "Puerto Rico",
                "Qatar",
                "Reunion",
                "Romania",
                "Russian Federation",
                "Russia",
                "Rwanda",
                "Saint Helena, Ascension and Tristan da Cunha",
                "Saint Kitts and Nevis",
                "Saint Lucia",
                "Saint Pierre and Miquelon",
                "Saint Vincent and the Grenadines",
                "Saint Vincent & the Grenadines",
                "St. Vincent and the Grenadines",
                "Samoa",
                "San Marino",
                "Sao Tome and Principe",
                "Saudi Arabia",
                "Senegal",
                "Serbia",
                "Seychelles",
                "Sierra Leone",
                "Singapore",
                "Slovakia",
                "Slovenia",
                "Solomon Islands",
                "Somalia",
                "South Africa",
                "South Georgia and the South Sandwich Islands",
                "South Sudan",
                "Spain",
                "Sri Lanka",
                "Sudan",
                "Suriname",
                "Svalbard and Jan Mayen",
                "Swaziland",
                "Sweden",
                "Switzerland",
                "Syrian Arab Republic",
                "Taiwan, Province of China",
                "Taiwan",
                "Tajikistan",
                "Tanzania, United Republic of",
                "Thailand",
                "Timor-Leste",
                "Togo",
                "Tokelau",
                "Tonga",
                "Trinidad and Tobago",
                "Tunisia",
                "Turkey",
                "Turkmenistan",
                "Turks and Caicos Islands",
                "Tuvalu",
                "Uganda",
                "Ukraine",
                "United Arab Emirates",
                "United States Minor Outlying Islands",
                "Uruguay",
                "Uzbekistan",
                "Vanuatu",
                "Venezuela, Bolivarian Republic of",
                "Venezuela",
                "Viet Nam",
                "Vietnam",
                "Virgin Islands, British",
                "Virgin Islands, U.S.",
                "Wallis and Futuna",
                "Western Sahara",
                "Yemen",
                "Zambia",
                "Zimbabwe",
            ],
        },
        "nationality name": {
            "required": True,
            "sqlalchemy_type": "assoc_proxy",
            "system_name": "nationality_name",
            "type": "string",
            "values": [
                "United Kingdom",
                "Canada",
                "France",
                "Germany",
                "Italy",
                "Netherlands",
                "United States",
                "Afghanistan",
                "Albania",
                "Algeria",
                "American Samoa",
                "Andorra",
                "Angola",
                "Anguilla",
                "Antarctica",
                "Antigua and Barbuda",
                "Argentina",
                "Armenia",
                "Aruba",
                "Australia",
                "Austria",
                "Azerbaijan",
                "Bahamas",
                "Bahrain",
                "Bangladesh",
                "Barbados",
                "Belarus",
                "Belgium",
                "Belize",
                "Benin",
                "Bermuda",
                "Bhutan",
                "Bolivia, Plurinational State of",
                "Bolivia",
                "Bosnia and Herzegovina",
                "Botswana",
                "Bouvet Island",
                "Brazil",
                "British Indian Ocean Territory",
                "Brunei Darussalam",
                "Brunei",
                "Bulgaria",
                "Burkina Faso",
                "Burundi",
                "Cambodia",
                "Cameroon",
                "Cape Verde",
                "Cayman Islands",
                "Central African Republic",
                "Chad",
                "Chile",
                "China",
                "Christmas Island",
                "Cocos (Keeling) Islands",
                "Colombia",
                "Comoros",
                "Congo",
                "Congo, the Democratic Republic of the",
                "Cook Islands",
                "Costa Rica",
                "Cote d'Ivoire",
                "Ivory Coast",
                "Croatia",
                "Cuba",
                "Cyprus",
                "Czech Republic",
                "Denmark",
                "Djibouti",
                "Dominica",
                "Dominican Republic",
                "Ecuador",
                "Egypt",
                "El Salvador",
                "Equatorial Guinea",
                "Eritrea",
                "Estonia",
                "Ethiopia",
                "Falkland Islands (Malvinas)",
                "Faroe Islands",
                "Fiji",
                "Finland",
                "French Guiana",
                "French Polynesia",
                "French Southern Territories",
                "Gabon",
                "Gambia",
                "Georgia",
                "Ghana",
                "Gibraltar",
                "Greece",
                "Greenland",
                "Grenada",
                "Guadeloupe",
                "Guam",
                "Guatemala",
                "Guernsey",
                "Guinea",
                "Guinea-Bissau",
                "Guyana",
                "Haiti",
                "Heard Island and McDonald Islands",
                "Holy See (Vatican City State)",
                "Honduras",
                "Hong Kong",
                "Hungary",
                "Iceland",
                "India",
                "Indonesia",
                "Iran, Islamic Republic of",
                "Iraq",
                "Ireland",
                "Isle of Man",
                "Israel",
                "Jamaica",
                "Japan",
                "Jersey",
                "Jordan",
                "Kazakhstan",
                "Kenya",
                "Kiribati",
                "Korea, Democratic People's Republic of",
                "Korea, Republic of",
                "South Korea",
                "Kuwait",
                "Kyrgyzstan",
                "Lao People's Democratic Republic",
                "Latvia",
                "Lebanon",
                "Lesotho",
                "Liberia",
                "Libyan Arab Jamahiriya",
                "Libya",
                "Liechtenstein",
                "Lithuania",
                "Luxembourg",
                "Macao",
                "Macedonia, the former Yugoslav Republic of",
                "Madagascar",
                "Malawi",
                "Malaysia",
                "Maldives",
                "Mali",
                "Malta",
                "Marshall Islands",
                "Martinique",
                "Mauritania",
                "Mauritius",
                "Mayotte",
                "Mexico",
                "Micronesia, Federated States of",
                "Moldova, Republic of",
                "Monaco",
                "Mongolia",
                "Montenegro",
                "Montserrat",
                "Morocco",
                "Mozambique",
                "Myanmar",
                "Burma",
                "Namibia",
                "Nauru",
                "Nepal",
                "Netherlands Antilles",
                "New Caledonia",
                "New Zealand",
                "Nicaragua",
                "Niger",
                "Nigeria",
                "Niue",
                "Norfolk Island",
                "Northern Mariana Islands",
                "Norway",
                "Oman",
                "Pakistan",
                "Palau",
                "Palestinian Territory, Occupied",
                "Panama",
                "Papua New Guinea",
                "Paraguay",
                "Peru",
                "Philippines",
                "Pitcairn",
                "Poland",
                "Portugal",
                "Puerto Rico",
                "Qatar",
                "Reunion",
                "Romania",
                "Russian Federation",
                "Russia",
                "Rwanda",
                "Saint Helena, Ascension and Tristan da Cunha",
                "Saint Kitts and Nevis",
                "Saint Lucia",
                "Saint Pierre and Miquelon",
                "Saint Vincent and the Grenadines",
                "Saint Vincent & the Grenadines",
                "St. Vincent and the Grenadines",
                "Samoa",
                "San Marino",
                "Sao Tome and Principe",
                "Saudi Arabia",
                "Senegal",
                "Serbia",
                "Seychelles",
                "Sierra Leone",
                "Singapore",
                "Slovakia",
                "Slovenia",
                "Solomon Islands",
                "Somalia",
                "South Africa",
                "South Georgia and the South Sandwich Islands",
                "South Sudan",
                "Spain",
                "Sri Lanka",
                "Sudan",
                "Suriname",
                "Svalbard and Jan Mayen",
                "Swaziland",
                "Sweden",
                "Switzerland",
                "Syrian Arab Republic",
                "Taiwan, Province of China",
                "Taiwan",
                "Tajikistan",
                "Tanzania, United Republic of",
                "Thailand",
                "Timor-Leste",
                "Togo",
                "Tokelau",
                "Tonga",
                "Trinidad and Tobago",
                "Tunisia",
                "Turkey",
                "Turkmenistan",
                "Turks and Caicos Islands",
                "Tuvalu",
                "Uganda",
                "Ukraine",
                "United Arab Emirates",
                "United States Minor Outlying Islands",
                "Uruguay",
                "Uzbekistan",
                "Vanuatu",
                "Venezuela, Bolivarian Republic of",
                "Venezuela",
                "Viet Nam",
                "Vietnam",
                "Virgin Islands, British",
                "Virgin Islands, U.S.",
                "Wallis and Futuna",
                "Western Sahara",
                "Yemen",
                "Zambia",
                "Zimbabwe",
            ],
        },
        "platform id": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "platform_id",
            "type": "id",
        },
        "platform type": {
            "foreign_table_type": TableTypes.REFERENCE,
            "multiple_values_allowed": False,
            "required": True,
            "second_level": False,
            "sqlalchemy_type": "relationship",
            "system_name": "platform_type",
            "type": "string",
            "values": [
                "Attack Craft",
                "Commercial aircraft",
                "Fishing Vessel",
                "High Speed Craft",
                "Law Enforcement",
                "Medical",
                "Merchant",
                "Naval - aircraft carrier",
                "Naval - amphib",
                "Naval - auxiliary",
                "Naval - cruiser",
                "Naval - destroyer",
                "Naval - ExCon",
                "Naval - fixed wing",
                "Naval - frigate",
                "Naval - minewarfare",
                "Naval - miscellaneous",
                "Naval - patrol",
                "Naval - rotary wing",
                "Naval - submarine",
                "Naval - survey",
                "Passenger vessel",
                "Pleasure Craft",
                "Research vessel",
                "Sailing vessel",
                "Search and Rescue",
                "Offshore support",
                "Civilian - uncrewed surface vehicle",
                "Civilian - uncrewed underwater vehicle",
                "Civilian - uncrewed air vehicle",
                "Naval - uncrewed surface vehicle",
                "Naval - uncrewed underwater vehicle",
                "Naval - uncrewed air vehicle",
            ],
        },
        "platform type name": {
            "required": True,
            "sqlalchemy_type": "assoc_proxy",
            "system_name": "platform_type_name",
            "type": "string",
            "values": [
                "Attack Craft",
                "Civilian - uncrewed air vehicle",
                "Civilian - uncrewed surface vehicle",
                "Civilian - uncrewed underwater vehicle",
                "Commercial aircraft",
                "Fishing Vessel",
                "High Speed Craft",
                "Law Enforcement",
                "Medical",
                "Merchant",
                "Naval - ExCon",
                "Naval - aircraft carrier",
                "Naval - amphib",
                "Naval - auxiliary",
                "Naval - cruiser",
                "Naval - destroyer",
                "Naval - fixed wing",
                "Naval - frigate",
                "Naval - minewarfare",
                "Naval - miscellaneous",
                "Naval - patrol",
                "Naval - rotary wing",
                "Naval - submarine",
                "Naval - survey",
                "Naval - uncrewed air vehicle",
                "Naval - uncrewed surface vehicle",
                "Naval - uncrewed underwater vehicle",
                "Offshore support",
                "Passenger vessel",
                "Pleasure Craft",
                "Research vessel",
                "Sailing vessel",
                "Search and Rescue",
            ],
        },
        "privacy": {
            "foreign_table_type": TableTypes.REFERENCE,
            "multiple_values_allowed": False,
            "required": True,
            "second_level": False,
            "sqlalchemy_type": "relationship",
            "system_name": "privacy",
            "type": "string",
            "values": [
                "Public",
                "Public Sensitive",
                "Private",
                "Private UK/IE",
                "Very Private UK/IE",
                "Private UK/IE/FR",
                "Very Private UK/IE/FR",
                "Very Private",
            ],
        },
        "privacy name": {
            "required": True,
            "sqlalchemy_type": "assoc_proxy",
            "system_name": "privacy_name",
            "type": "string",
            "values": [
                "Public",
                "Public Sensitive",
                "Private",
                "Private UK/IE",
                "Very Private UK/IE",
                "Private UK/IE/FR",
                "Very Private UK/IE/FR",
                "Very Private",
            ],
        },
        "quadgraph": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "quadgraph",
            "type": "string",
            "values": [],
        },
        "trigraph": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "trigraph",
            "type": "string",
            "values": [],
        },
        "wargame participations": {
            "required": True,
            "sqlalchemy_type": "assoc_proxy",
            "system_name": "wargame_participations",
            "type": "string",
            "values": [],
        },
    }

    del col_data["nationality"]["ids"]
    del col_data["platform type"]["ids"]
    del col_data["privacy"]["ids"]

    pprint(col_data)

    assert col_data == correct_col_data


def test_column_data_wargame():
    store = DataStore("", "", "", 0, ":memory:", db_type="sqlite")
    store.initialise()
    with store.session_scope():
        store.populate_reference()
        store.populate_metadata()

    col_data = create_column_data(store, store.db_classes.Wargame)

    correct_col_data = {
        "child serials": {
            "foreign_table_type": TableTypes.METADATA,
            "ids": [],
            "multiple_values_allowed": True,
            "required": True,
            "second_level": False,
            "sqlalchemy_type": "relationship",
            "system_name": "child_serials",
            "type": "string",
            "values": [],
        },
        "created date": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "created_date",
            "type": "datetime",
        },
        "end": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "end",
            "type": "datetime",
        },
        "name": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "name",
            "type": "string",
            "values": [],
        },
        "participants platform name": {
            "required": True,
            "sqlalchemy_type": "assoc_proxy",
            "system_name": "participants_platform_name",
            "type": "string",
            "values": [],
        },
        "privacy": {
            "foreign_table_type": TableTypes.REFERENCE,
            "multiple_values_allowed": False,
            "required": True,
            "second_level": False,
            "sqlalchemy_type": "relationship",
            "system_name": "privacy",
            "type": "string",
            "values": [
                "Public",
                "Public Sensitive",
                "Private",
                "Private UK/IE",
                "Very Private UK/IE",
                "Private UK/IE/FR",
                "Very Private UK/IE/FR",
                "Very Private",
            ],
        },
        "privacy name": {
            "required": True,
            "sqlalchemy_type": "assoc_proxy",
            "system_name": "privacy_name",
            "type": "string",
            "values": [
                "Public",
                "Public Sensitive",
                "Private",
                "Private UK/IE",
                "Very Private UK/IE",
                "Private UK/IE/FR",
                "Very Private UK/IE/FR",
                "Very Private",
            ],
        },
        "series": {
            "foreign_table_type": TableTypes.METADATA,
            "ids": [],
            "multiple_values_allowed": False,
            "required": True,
            "second_level": False,
            "sqlalchemy_type": "relationship",
            "system_name": "series",
            "type": "string",
            "values": [],
        },
        "series name": {
            "required": True,
            "sqlalchemy_type": "assoc_proxy",
            "system_name": "series_name",
            "type": "string",
            "values": [],
        },
        "start": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "start",
            "type": "datetime",
        },
        "wargame id": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "wargame_id",
            "type": "id",
        },
    }

    del col_data["privacy"]["ids"]

    print(pprint(col_data))

    assert col_data == correct_col_data


def test_column_data_platform_type():
    store = DataStore("", "", "", 0, ":memory:", db_type="sqlite")
    store.initialise()
    with store.session_scope():
        store.populate_reference()
        store.populate_metadata()

    col_data = create_column_data(store, store.db_classes.PlatformType)

    correct_col_data = {
        "created date": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "created_date",
            "type": "datetime",
        },
        "default data interval secs": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "default_data_interval_secs",
            "type": "int",
        },
        "name": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "name",
            "type": "string",
            "values": [
                "Attack Craft",
                "Civilian - uncrewed air vehicle",
                "Civilian - uncrewed surface vehicle",
                "Civilian - uncrewed underwater vehicle",
                "Commercial aircraft",
                "Fishing Vessel",
                "High Speed Craft",
                "Law Enforcement",
                "Medical",
                "Merchant",
                "Naval - ExCon",
                "Naval - aircraft carrier",
                "Naval - amphib",
                "Naval - auxiliary",
                "Naval - cruiser",
                "Naval - destroyer",
                "Naval - fixed wing",
                "Naval - frigate",
                "Naval - minewarfare",
                "Naval - miscellaneous",
                "Naval - patrol",
                "Naval - rotary wing",
                "Naval - submarine",
                "Naval - survey",
                "Naval - uncrewed air vehicle",
                "Naval - uncrewed surface vehicle",
                "Naval - uncrewed underwater vehicle",
                "Offshore support",
                "Passenger vessel",
                "Pleasure Craft",
                "Research vessel",
                "Sailing vessel",
                "Search and Rescue",
            ],
        },
        "platform type id": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "platform_type_id",
            "type": "id",
        },
    }

    print(pprint(col_data))

    assert col_data == correct_col_data


def test_column_data_privacies():
    store = DataStore("", "", "", 0, ":memory:", db_type="sqlite")
    store.initialise()
    with store.session_scope():
        store.populate_reference()
        store.populate_metadata()

    col_data = create_column_data(store, store.db_classes.Privacy)

    print(pprint(col_data))

    assert col_data == {
        "created date": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "created_date",
            "type": "datetime",
        },
        "level": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "level",
            "type": "int",
        },
        "name": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "name",
            "type": "string",
            "values": [
                "Private",
                "Private UK/IE",
                "Private UK/IE/FR",
                "Public",
                "Public Sensitive",
                "Very Private",
                "Very Private UK/IE",
                "Very Private UK/IE/FR",
            ],
        },
        "privacy id": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "privacy_id",
            "type": "id",
        },
    }


def test_column_data_state():
    store = DataStore("", "", "", 0, ":memory:", db_type="sqlite")
    store.initialise()
    with store.session_scope():
        store.populate_reference()
        store.populate_metadata()

    col_data = create_column_data(store, store.db_classes.State)

    print(pprint(col_data))

    del col_data["platform"]["ids"]
    del col_data["privacy"]["ids"]
    del col_data["sensor"]["ids"]

    assert col_data == {
        "course": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "course",
            "type": "float",
        },
        "created date": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "created_date",
            "type": "datetime",
        },
        "elevation": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "elevation",
            "type": "float",
        },
        "heading": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "heading",
            "type": "float",
        },
        "location": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "location",
            "type": "geometry",
        },
        "platform": {
            "foreign_table_type": TableTypes.METADATA,
            "multiple_values_allowed": False,
            "required": True,
            "second_level": True,
            "sqlalchemy_type": "relationship",
            "system_name": "platform",
            "type": "string",
            "values": [
                "ADRI / A643 / United Kingdom",
                "JEAN / A816 / United Kingdom",
                "NARV / C045 / United Kingdom",
                "SPAR / P543 / France",
            ],
        },
        "platform name": {
            "required": True,
            "sqlalchemy_type": "assoc_proxy",
            "system_name": "platform_name",
            "type": "string",
            "values": ["ADRI", "JEAN", "NARV", "SPAR"],
        },
        "privacy": {
            "foreign_table_type": TableTypes.REFERENCE,
            "multiple_values_allowed": False,
            "required": False,
            "second_level": False,
            "sqlalchemy_type": "relationship",
            "system_name": "privacy",
            "type": "string",
            "values": [
                "Public",
                "Public Sensitive",
                "Private",
                "Private UK/IE",
                "Very Private UK/IE",
                "Private UK/IE/FR",
                "Very Private UK/IE/FR",
                "Very Private",
            ],
        },
        "privacy name": {
            "required": False,
            "sqlalchemy_type": "assoc_proxy",
            "system_name": "privacy_name",
            "type": "string",
            "values": [
                "Public",
                "Public Sensitive",
                "Private",
                "Private UK/IE",
                "Very Private UK/IE",
                "Private UK/IE/FR",
                "Very Private UK/IE/FR",
                "Very Private",
            ],
        },
        "remarks": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "remarks",
            "type": "string",
        },
        "sensor": {
            "foreign_table_type": TableTypes.METADATA,
            "multiple_values_allowed": False,
            "required": True,
            "second_level": False,
            "sqlalchemy_type": "relationship",
            "system_name": "sensor",
            "type": "string",
            "values": [
                "GPS / ADRI / A643 / United Kingdom",
                "INS / ADRI / A643 / United Kingdom",
                "Radar / ADRI / A643 / United Kingdom",
                "Periscope / ADRI / A643 / United Kingdom",
                "GPS / JEAN / A816 / United Kingdom",
                "GPS / SPAR / P543 / France",
            ],
        },
        "sensor name": {
            "required": True,
            "sqlalchemy_type": "assoc_proxy",
            "system_name": "sensor_name",
            "type": "string",
            "values": ["GPS", "INS", "Periscope", "Radar"],
        },
        "source": {
            "foreign_table_type": TableTypes.METADATA,
            "multiple_values_allowed": False,
            "ids": [],
            "required": True,
            "second_level": False,
            "sqlalchemy_type": "relationship",
            "system_name": "source",
            "type": "string",
            "values": [],
        },
        "source reference": {
            "required": True,
            "sqlalchemy_type": "assoc_proxy",
            "system_name": "source_reference",
            "type": "string",
            "values": [],
        },
        "speed": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "speed",
            "type": "float",
        },
        "state id": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "state_id",
            "type": "id",
        },
        "time": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "time",
            "type": "datetime",
        },
    }


def test_edit_data_platform_type():
    store = DataStore("", "", "", 0, ":memory:", db_type="sqlite")
    store.initialise()
    with store.session_scope():
        store.populate_reference()
        store.populate_metadata()

    col_data = create_column_data(store, store.db_classes.PlatformType)

    edit_data = convert_column_data_to_edit_data(col_data)

    pprint(edit_data)

    assert edit_data == {
        "name": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "name",
            "type": "string",
        },
        "default data interval secs": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "default_data_interval_secs",
            "type": "int",
        },
    }


def test_edit_data_wargame():
    store = DataStore("", "", "", 0, ":memory:", db_type="sqlite")
    store.initialise()
    with store.session_scope():
        store.populate_reference()
        store.populate_metadata()

    col_data = create_column_data(store, store.db_classes.Wargame)

    edit_data = convert_column_data_to_edit_data(col_data)

    pprint(edit_data)

    correct_edit_data = {
        "end": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "end",
            "type": "datetime",
        },
        "name": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "name",
            "type": "string",
        },
        "privacy": {
            "foreign_table_type": TableTypes.REFERENCE,
            "multiple_values_allowed": False,
            "required": True,
            "second_level": False,
            "sqlalchemy_type": "relationship",
            "system_name": "privacy",
            "type": "string",
            "values": [
                "Public",
                "Public Sensitive",
                "Private",
                "Private UK/IE",
                "Very Private UK/IE",
                "Private UK/IE/FR",
                "Very Private UK/IE/FR",
                "Very Private",
            ],
        },
        "series": {
            "foreign_table_type": TableTypes.METADATA,
            "ids": [],
            "multiple_values_allowed": False,
            "required": True,
            "second_level": False,
            "sqlalchemy_type": "relationship",
            "system_name": "series",
            "type": "string",
            "values": [],
        },
        "start": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "start",
            "type": "datetime",
        },
    }

    del edit_data["privacy"]["ids"]

    assert edit_data == correct_edit_data


def test_edit_data_privacy():
    store = DataStore("", "", "", 0, ":memory:", db_type="sqlite")
    store.initialise()
    with store.session_scope():
        store.populate_reference()
        store.populate_metadata()

    col_data = create_column_data(store, store.db_classes.Privacy)

    edit_data = convert_column_data_to_edit_data(col_data)

    pprint(edit_data)

    assert edit_data == {
        "level": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "level",
            "type": "int",
        },
        "name": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "name",
            "type": "string",
        },
    }


def test_edit_data_platform():
    store = DataStore("", "", "", 0, ":memory:", db_type="sqlite")
    store.initialise()
    with store.session_scope():
        store.populate_reference()
        store.populate_metadata()

    col_data = create_column_data(store, store.db_classes.Platform)

    edit_data = convert_column_data_to_edit_data(col_data)

    del edit_data["privacy"]["ids"]
    del edit_data["nationality"]["ids"]
    del edit_data["platform type"]["ids"]
    # del edit_data["participations"]["ids"]

    pprint(edit_data)

    assert edit_data == {
        "identifier": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "identifier",
            "type": "string",
        },
        "name": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "name",
            "type": "string",
        },
        "nationality": {
            "foreign_table_type": TableTypes.REFERENCE,
            "multiple_values_allowed": False,
            "required": True,
            "second_level": False,
            "sqlalchemy_type": "relationship",
            "system_name": "nationality",
            "type": "string",
            "values": [
                "United Kingdom",
                "Canada",
                "France",
                "Germany",
                "Italy",
                "Netherlands",
                "United States",
                "Afghanistan",
                "Albania",
                "Algeria",
                "American Samoa",
                "Andorra",
                "Angola",
                "Anguilla",
                "Antarctica",
                "Antigua and Barbuda",
                "Argentina",
                "Armenia",
                "Aruba",
                "Australia",
                "Austria",
                "Azerbaijan",
                "Bahamas",
                "Bahrain",
                "Bangladesh",
                "Barbados",
                "Belarus",
                "Belgium",
                "Belize",
                "Benin",
                "Bermuda",
                "Bhutan",
                "Bolivia, Plurinational State of",
                "Bolivia",
                "Bosnia and Herzegovina",
                "Botswana",
                "Bouvet Island",
                "Brazil",
                "British Indian Ocean Territory",
                "Brunei Darussalam",
                "Brunei",
                "Bulgaria",
                "Burkina Faso",
                "Burundi",
                "Cambodia",
                "Cameroon",
                "Cape Verde",
                "Cayman Islands",
                "Central African Republic",
                "Chad",
                "Chile",
                "China",
                "Christmas Island",
                "Cocos (Keeling) Islands",
                "Colombia",
                "Comoros",
                "Congo",
                "Congo, the Democratic Republic of the",
                "Cook Islands",
                "Costa Rica",
                "Cote d'Ivoire",
                "Ivory Coast",
                "Croatia",
                "Cuba",
                "Cyprus",
                "Czech Republic",
                "Denmark",
                "Djibouti",
                "Dominica",
                "Dominican Republic",
                "Ecuador",
                "Egypt",
                "El Salvador",
                "Equatorial Guinea",
                "Eritrea",
                "Estonia",
                "Ethiopia",
                "Falkland Islands (Malvinas)",
                "Faroe Islands",
                "Fiji",
                "Finland",
                "French Guiana",
                "French Polynesia",
                "French Southern Territories",
                "Gabon",
                "Gambia",
                "Georgia",
                "Ghana",
                "Gibraltar",
                "Greece",
                "Greenland",
                "Grenada",
                "Guadeloupe",
                "Guam",
                "Guatemala",
                "Guernsey",
                "Guinea",
                "Guinea-Bissau",
                "Guyana",
                "Haiti",
                "Heard Island and McDonald Islands",
                "Holy See (Vatican City State)",
                "Honduras",
                "Hong Kong",
                "Hungary",
                "Iceland",
                "India",
                "Indonesia",
                "Iran, Islamic Republic of",
                "Iraq",
                "Ireland",
                "Isle of Man",
                "Israel",
                "Jamaica",
                "Japan",
                "Jersey",
                "Jordan",
                "Kazakhstan",
                "Kenya",
                "Kiribati",
                "Korea, Democratic People's Republic of",
                "Korea, Republic of",
                "South Korea",
                "Kuwait",
                "Kyrgyzstan",
                "Lao People's Democratic Republic",
                "Latvia",
                "Lebanon",
                "Lesotho",
                "Liberia",
                "Libyan Arab Jamahiriya",
                "Libya",
                "Liechtenstein",
                "Lithuania",
                "Luxembourg",
                "Macao",
                "Macedonia, the former Yugoslav Republic of",
                "Madagascar",
                "Malawi",
                "Malaysia",
                "Maldives",
                "Mali",
                "Malta",
                "Marshall Islands",
                "Martinique",
                "Mauritania",
                "Mauritius",
                "Mayotte",
                "Mexico",
                "Micronesia, Federated States of",
                "Moldova, Republic of",
                "Monaco",
                "Mongolia",
                "Montenegro",
                "Montserrat",
                "Morocco",
                "Mozambique",
                "Myanmar",
                "Burma",
                "Namibia",
                "Nauru",
                "Nepal",
                "Netherlands Antilles",
                "New Caledonia",
                "New Zealand",
                "Nicaragua",
                "Niger",
                "Nigeria",
                "Niue",
                "Norfolk Island",
                "Northern Mariana Islands",
                "Norway",
                "Oman",
                "Pakistan",
                "Palau",
                "Palestinian Territory, Occupied",
                "Panama",
                "Papua New Guinea",
                "Paraguay",
                "Peru",
                "Philippines",
                "Pitcairn",
                "Poland",
                "Portugal",
                "Puerto Rico",
                "Qatar",
                "Reunion",
                "Romania",
                "Russian Federation",
                "Russia",
                "Rwanda",
                "Saint Helena, Ascension and Tristan da Cunha",
                "Saint Kitts and Nevis",
                "Saint Lucia",
                "Saint Pierre and Miquelon",
                "Saint Vincent and the Grenadines",
                "Saint Vincent & the Grenadines",
                "St. Vincent and the Grenadines",
                "Samoa",
                "San Marino",
                "Sao Tome and Principe",
                "Saudi Arabia",
                "Senegal",
                "Serbia",
                "Seychelles",
                "Sierra Leone",
                "Singapore",
                "Slovakia",
                "Slovenia",
                "Solomon Islands",
                "Somalia",
                "South Africa",
                "South Georgia and the South Sandwich Islands",
                "South Sudan",
                "Spain",
                "Sri Lanka",
                "Sudan",
                "Suriname",
                "Svalbard and Jan Mayen",
                "Swaziland",
                "Sweden",
                "Switzerland",
                "Syrian Arab Republic",
                "Taiwan, Province of China",
                "Taiwan",
                "Tajikistan",
                "Tanzania, United Republic of",
                "Thailand",
                "Timor-Leste",
                "Togo",
                "Tokelau",
                "Tonga",
                "Trinidad and Tobago",
                "Tunisia",
                "Turkey",
                "Turkmenistan",
                "Turks and Caicos Islands",
                "Tuvalu",
                "Uganda",
                "Ukraine",
                "United Arab Emirates",
                "United States Minor Outlying Islands",
                "Uruguay",
                "Uzbekistan",
                "Vanuatu",
                "Venezuela, Bolivarian Republic of",
                "Venezuela",
                "Viet Nam",
                "Vietnam",
                "Virgin Islands, British",
                "Virgin Islands, U.S.",
                "Wallis and Futuna",
                "Western Sahara",
                "Yemen",
                "Zambia",
                "Zimbabwe",
            ],
        },
        "platform type": {
            "foreign_table_type": TableTypes.REFERENCE,
            "multiple_values_allowed": False,
            "required": True,
            "second_level": False,
            "sqlalchemy_type": "relationship",
            "system_name": "platform_type",
            "type": "string",
            "values": [
                "Attack Craft",
                "Commercial aircraft",
                "Fishing Vessel",
                "High Speed Craft",
                "Law Enforcement",
                "Medical",
                "Merchant",
                "Naval - aircraft carrier",
                "Naval - amphib",
                "Naval - auxiliary",
                "Naval - cruiser",
                "Naval - destroyer",
                "Naval - ExCon",
                "Naval - fixed wing",
                "Naval - frigate",
                "Naval - minewarfare",
                "Naval - miscellaneous",
                "Naval - patrol",
                "Naval - rotary wing",
                "Naval - submarine",
                "Naval - survey",
                "Passenger vessel",
                "Pleasure Craft",
                "Research vessel",
                "Sailing vessel",
                "Search and Rescue",
                "Offshore support",
                "Civilian - uncrewed surface vehicle",
                "Civilian - uncrewed underwater vehicle",
                "Civilian - uncrewed air vehicle",
                "Naval - uncrewed surface vehicle",
                "Naval - uncrewed underwater vehicle",
                "Naval - uncrewed air vehicle",
            ],
        },
        "privacy": {
            "foreign_table_type": TableTypes.REFERENCE,
            "multiple_values_allowed": False,
            "required": True,
            "second_level": False,
            "sqlalchemy_type": "relationship",
            "system_name": "privacy",
            "type": "string",
            "values": [
                "Public",
                "Public Sensitive",
                "Private",
                "Private UK/IE",
                "Very Private UK/IE",
                "Private UK/IE/FR",
                "Very Private UK/IE/FR",
                "Very Private",
            ],
        },
        "quadgraph": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "quadgraph",
            "type": "string",
        },
        "trigraph": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "trigraph",
            "type": "string",
        },
    }


def test_edit_data_state():
    store = DataStore("", "", "", 0, ":memory:", db_type="sqlite")
    store.initialise()
    with store.session_scope():
        store.populate_reference()
        store.populate_metadata()

    col_data = create_column_data(store, store.db_classes.State)

    edit_data = convert_column_data_to_edit_data(col_data)

    del edit_data["sensor"]["ids"]
    del edit_data["privacy"]["ids"]

    pprint(edit_data)

    assert edit_data == {
        "course": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "course",
            "type": "float",
        },
        "elevation": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "elevation",
            "type": "float",
        },
        "heading": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "heading",
            "type": "float",
        },
        "privacy": {
            "foreign_table_type": TableTypes.REFERENCE,
            "multiple_values_allowed": False,
            "required": False,
            "second_level": False,
            "sqlalchemy_type": "relationship",
            "system_name": "privacy",
            "type": "string",
            "values": [
                "Public",
                "Public Sensitive",
                "Private",
                "Private UK/IE",
                "Very Private UK/IE",
                "Private UK/IE/FR",
                "Very Private UK/IE/FR",
                "Very Private",
            ],
        },
        "remarks": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "remarks",
            "type": "string",
        },
        "sensor": {
            "foreign_table_type": TableTypes.METADATA,
            "multiple_values_allowed": False,
            "required": True,
            "second_level": False,
            "sqlalchemy_type": "relationship",
            "system_name": "sensor",
            "type": "string",
            "values": [
                "GPS / ADRI / A643 / United Kingdom",
                "INS / ADRI / A643 / United Kingdom",
                "Radar / ADRI / A643 / United Kingdom",
                "Periscope / ADRI / A643 / United Kingdom",
                "GPS / JEAN / A816 / United Kingdom",
                "GPS / SPAR / P543 / France",
            ],
        },
        "source": {
            "foreign_table_type": TableTypes.METADATA,
            "multiple_values_allowed": False,
            "ids": [],
            "required": True,
            "second_level": False,
            "sqlalchemy_type": "relationship",
            "system_name": "source",
            "type": "string",
            "values": [],
        },
        "speed": {
            "required": False,
            "sqlalchemy_type": "column",
            "system_name": "speed",
            "type": "float",
        },
        "time": {
            "required": True,
            "sqlalchemy_type": "column",
            "system_name": "time",
            "type": "datetime",
        },
    }
