CREATE TABLE pepys."Contacts"
(
    contact_id     UUID                        NOT NULL,
    name           VARCHAR(150)                NOT NULL,
    sensor_id      UUID                        NOT NULL,
    time           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    bearing        DOUBLE PRECISION,
    rel_bearing    DOUBLE PRECISION,
    freq           DOUBLE PRECISION,
    location       geometry(POINT, 4326),
    major          DOUBLE PRECISION,
    minor          DOUBLE PRECISION,
    orientation    DOUBLE PRECISION,
    classification VARCHAR(150),
    confidence     VARCHAR(150),
    contact_type   VARCHAR(150),
    mla            DOUBLE PRECISION,
    sla            DOUBLE PRECISION,
    subject_id     UUID                        NOT NULL,
    source_id      UUID                        NOT NULL,
    privacy_id     UUID,
    created_date   TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (contact_id),
    FOREIGN KEY (sensor_id) REFERENCES pepys."Sensors" (sensor_id),
    FOREIGN KEY (subject_id) REFERENCES pepys."Platforms" (platform_id),
    FOREIGN KEY (source_id) REFERENCES pepys."Datafiles" (datafile_id),
    FOREIGN KEY (privacy_id) REFERENCES pepys."Privacies" (privacy_id)
)
