HOUR_OFFSET = 3600
TIMEZONE_MAPPINGS = {
    "A": 1 * HOUR_OFFSET,
    "B": 2 * HOUR_OFFSET,
    "C": 3 * HOUR_OFFSET,
    "D": 4 * HOUR_OFFSET,
    "E": 5 * HOUR_OFFSET,
    "F": 6 * HOUR_OFFSET,
    "G": 7 * HOUR_OFFSET,
    "H": 8 * HOUR_OFFSET,
    "I": 9 * HOUR_OFFSET,
    "K": 10 * HOUR_OFFSET,
    "L": 11 * HOUR_OFFSET,
    "M": 12 * HOUR_OFFSET,
    "N": -1 * HOUR_OFFSET,
    "O": -2 * HOUR_OFFSET,
    "P": -3 * HOUR_OFFSET,
    "Q": -4 * HOUR_OFFSET,
    "R": -5 * HOUR_OFFSET,
    "S": -6 * HOUR_OFFSET,
    "T": -7 * HOUR_OFFSET,
    "U": -8 * HOUR_OFFSET,
    "V": -9 * HOUR_OFFSET,
    "W": -10 * HOUR_OFFSET,
    "X": -11 * HOUR_OFFSET,
    "Y": -12 * HOUR_OFFSET,
    "Z": 0,
}
