"""update foreign keys

Revision ID: 4e5e6642c087
Revises: 5154f7db278d
Create Date: 2020-05-09 14:22:12.281565

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4e5e6642c087"
down_revision = "5154f7db278d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Comments", schema="pepys") as batch_op:
        batch_op.alter_column("platform_id", existing_type=postgresql.UUID(), nullable=True)
        batch_op.create_foreign_key(
            None, "CommentTypes", ["comment_type_id"], ["comment_type_id"], referent_schema="pepys"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Comments", schema="pepys") as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column("platform_id", existing_type=postgresql.UUID(), nullable=False)

    # ### end Alembic commands ###
