"""Add cascading on delete

Revision ID: 35f69a534d88
Revises: d154cad9087f
Create Date: 2020-11-18 12:42:05.362966+00:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "35f69a534d88"
down_revision = "d154cad9087f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_Activations_source_id_Datafiles", "Activations", schema="pepys", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_Activations_source_id_Datafiles"),
        "Activations",
        "Datafiles",
        ["source_id"],
        ["datafile_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="cascade",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_Comments_source_id_Datafiles", "Comments", schema="pepys", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_Comments_source_id_Datafiles"),
        "Comments",
        "Datafiles",
        ["source_id"],
        ["datafile_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="cascade",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_Contacts_source_id_Datafiles", "Contacts", schema="pepys", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_Contacts_source_id_Datafiles"),
        "Contacts",
        "Datafiles",
        ["source_id"],
        ["datafile_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="cascade",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_Geometries_source_id_Datafiles", "Geometries", schema="pepys", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_Geometries_source_id_Datafiles"),
        "Geometries",
        "Datafiles",
        ["source_id"],
        ["datafile_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="cascade",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_LogsHoldings_source_id_Datafiles", "LogsHoldings", schema="pepys", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_LogsHoldings_source_id_Datafiles"),
        "LogsHoldings",
        "Datafiles",
        ["source_id"],
        ["datafile_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="cascade",
        ondelete="CASCADE",
    )
    op.drop_constraint("fk_Media_source_id_Datafiles", "Media", schema="pepys", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_Media_source_id_Datafiles"),
        "Media",
        "Datafiles",
        ["source_id"],
        ["datafile_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="cascade",
        ondelete="CASCADE",
    )
    op.drop_constraint("fk_Sensors_host_Platforms", "Sensors", schema="pepys", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_Sensors_host_Platforms"),
        "Sensors",
        "Platforms",
        ["host"],
        ["platform_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="cascade",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_States_source_id_Datafiles", "States", schema="pepys", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_States_source_id_Datafiles"),
        "States",
        "Datafiles",
        ["source_id"],
        ["datafile_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="cascade",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_States_source_id_Datafiles"), "States", schema="pepys", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_States_source_id_Datafiles",
        "States",
        "Datafiles",
        ["source_id"],
        ["datafile_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_Sensors_host_Platforms"), "Sensors", schema="pepys", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_Sensors_host_Platforms",
        "Sensors",
        "Platforms",
        ["host"],
        ["platform_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_Media_source_id_Datafiles"), "Media", schema="pepys", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_Media_source_id_Datafiles",
        "Media",
        "Datafiles",
        ["source_id"],
        ["datafile_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_LogsHoldings_source_id_Datafiles"),
        "LogsHoldings",
        schema="pepys",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_LogsHoldings_source_id_Datafiles",
        "LogsHoldings",
        "Datafiles",
        ["source_id"],
        ["datafile_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_Geometries_source_id_Datafiles"), "Geometries", schema="pepys", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_Geometries_source_id_Datafiles",
        "Geometries",
        "Datafiles",
        ["source_id"],
        ["datafile_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_Contacts_source_id_Datafiles"), "Contacts", schema="pepys", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_Contacts_source_id_Datafiles",
        "Contacts",
        "Datafiles",
        ["source_id"],
        ["datafile_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_Comments_source_id_Datafiles"), "Comments", schema="pepys", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_Comments_source_id_Datafiles",
        "Comments",
        "Datafiles",
        ["source_id"],
        ["datafile_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_Activations_source_id_Datafiles"),
        "Activations",
        schema="pepys",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_Activations_source_id_Datafiles",
        "Activations",
        "Datafiles",
        ["source_id"],
        ["datafile_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="CASCADE",
    )
    # ### end Alembic commands ###
