"""Make name nullable for activation and geometry

Revision ID: 475c0ecdf9cd
Revises: 4752cdff2570
Create Date: 2020-06-29 09:48:35.536951

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "475c0ecdf9cd"
down_revision = "4752cdff2570"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Activations", schema="pepys") as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(length=150), nullable=True)

    with op.batch_alter_table("Geometries", schema="pepys") as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(length=150), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Geometries", schema="pepys") as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(length=150), nullable=False)

    with op.batch_alter_table("Activations", schema="pepys") as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(length=150), nullable=False)

    # ### end Alembic commands ###
