"""Add foreign key for GeomSubType.parent

Revision ID: ef8239cb0492
Revises: 6f625922f61c
Create Date: 2020-05-25 10:59:43.694513

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "ef8239cb0492"
down_revision = "6f625922f61c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("GeometrySubTypes", schema="pepys") as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_GeometrySubTypes_parent_GeometryTypes"),
            "GeometryTypes",
            ["parent"],
            ["geo_type_id"],
            referent_schema="pepys",
            onupdate="cascade",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("GeometrySubTypes", schema="pepys") as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_GeometrySubTypes_parent_GeometryTypes"), type_="foreignkey"
        )

    # ### end Alembic commands ###
