"""Add 3 new indexes

Revision ID: d7ed5c1d4f24
Revises: 00116b58f22e
Create Date: 2020-12-24 09:14:58.090047+00:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "d7ed5c1d4f24"
down_revision = "00116b58f22e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_comments_comp_platform_source",
        "Comments",
        ["platform_id", "source_id"],
        schema="pepys",
        unique=False,
    )
    op.create_index(
        "idx_contacts_comp_sensor_source",
        "Contacts",
        ["sensor_id", "source_id"],
        schema="pepys",
        unique=False,
    )
    op.create_index(
        "idx_states_comp_sensor_source",
        "States",
        ["sensor_id", "source_id"],
        schema="pepys",
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_comments_comp_platform_source", "Comments", schema="pepys")
    op.drop_index("idx_contacts_comp_sensor_source", "Contacts", schema="pepys")
    op.drop_index("idx_states_comp_sensor_source", "States", schema="pepys")
    # ### end Alembic commands ###
