"""fix simulated attribute of datafile

Revision ID: 8e35dda19305
Revises: 4e5e6642c087
Create Date: 2020-05-10 16:28:20.675097

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8e35dda19305"
down_revision = "4e5e6642c087"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Datafiles", schema="pepys") as batch_op:
        batch_op.alter_column("simulated", existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Datafiles", schema="pepys") as batch_op:
        batch_op.alter_column("simulated", existing_type=sa.BOOLEAN(), nullable=True)

    # ### end Alembic commands ###
