"""Update nullability of columns of Activations

Revision ID: b311affac706
Revises: 0189cb24812f
Create Date: 2020-06-30 14:28:45.035025

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import pepys_import

# revision identifiers, used by Alembic.
revision = "b311affac706"
down_revision = "0189cb24812f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Activations", schema="pepys") as batch_op:
        batch_op.alter_column("end", existing_type=postgresql.TIMESTAMP(), nullable=True)
        batch_op.alter_column("start", existing_type=postgresql.TIMESTAMP(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Activations", schema="pepys") as batch_op:
        batch_op.alter_column("start", existing_type=postgresql.TIMESTAMP(), nullable=False)
        batch_op.alter_column("end", existing_type=postgresql.TIMESTAMP(), nullable=False)

    # ### end Alembic commands ###
