"""Add track number to Contacts table

Revision ID: 4752cdff2570
Revises: 3c25e6a37cd2
Create Date: 2020-06-28 12:47:06.864554

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4752cdff2570"
down_revision = "3c25e6a37cd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Contacts", schema="pepys") as batch_op:
        batch_op.add_column(sa.Column("track_number", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Contacts", schema="pepys") as batch_op:
        batch_op.drop_column("track_number")
    # ### end Alembic commands ###
