"""Add level attribute to Privacies Table

Revision ID: d96db9a0620f
Revises: 30194fdfc033
Create Date: 2020-06-05 12:42:57.737339

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d96db9a0620f"
down_revision = "30194fdfc033"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Privacies", schema="pepys") as batch_op:
        batch_op.add_column(sa.Column("level", sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Privacies", schema="pepys") as batch_op:
        batch_op.drop_column("level")
    # ### end Alembic commands ###
