"""Add priority field to Nationality

Revision ID: 91d0713df209
Revises: 6f625922f61c
Create Date: 2020-05-25 13:18:08.228136

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

import pepys_import

# revision identifiers, used by Alembic.
revision = "91d0713df209"
down_revision = "6f625922f61c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Nationalities", schema="pepys") as batch_op:
        batch_op.add_column(sa.Column("priority", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Nationalities", schema="pepys") as batch_op:
        batch_op.drop_column("priority")

    # ### end Alembic commands ###
