"""Add remark column

Revision ID: 0189cb24812f
Revises: b06718e52214
Create Date: 2020-06-30 14:23:50.601096

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0189cb24812f"
down_revision = "b06718e52214"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Activations", schema="pepys") as batch_op:
        batch_op.add_column(sa.Column("remarks", sa.Text(), nullable=True))

    with op.batch_alter_table("Comments", schema="pepys") as batch_op:
        batch_op.alter_column(
            "content",
            existing_type=sa.VARCHAR(length=150),
            type_=sa.Text(),
            existing_nullable=False,
        )

    with op.batch_alter_table("Contacts", schema="pepys") as batch_op:
        batch_op.add_column(sa.Column("remarks", sa.Text(), nullable=True))

    with op.batch_alter_table("Geometries", schema="pepys") as batch_op:
        batch_op.add_column(sa.Column("remarks", sa.Text(), nullable=True))

    with op.batch_alter_table("LogsHoldings", schema="pepys") as batch_op:
        batch_op.alter_column(
            "comment",
            existing_type=sa.VARCHAR(length=150),
            type_=sa.Text(),
            existing_nullable=False,
        )

    with op.batch_alter_table("Media", schema="pepys") as batch_op:
        batch_op.add_column(sa.Column("remarks", sa.Text(), nullable=True))

    with op.batch_alter_table("States", schema="pepys") as batch_op:
        batch_op.add_column(sa.Column("remarks", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("States", schema="pepys") as batch_op:
        batch_op.drop_column("remarks")

    with op.batch_alter_table("Media", schema="pepys") as batch_op:
        batch_op.drop_column("remarks")

    with op.batch_alter_table("LogsHoldings", schema="pepys") as batch_op:
        batch_op.alter_column(
            "comment",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(length=150),
            existing_nullable=False,
        )

    with op.batch_alter_table("Geometries", schema="pepys") as batch_op:
        batch_op.drop_column("remarks")

    with op.batch_alter_table("Contacts", schema="pepys") as batch_op:
        batch_op.drop_column("remarks")

    with op.batch_alter_table("Comments", schema="pepys") as batch_op:
        batch_op.alter_column(
            "content",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(length=150),
            existing_nullable=False,
        )

    with op.batch_alter_table("Activations", schema="pepys") as batch_op:
        batch_op.drop_column("remarks")

    # ### end Alembic commands ###
