"""Add SRID for Geometry field

Revision ID: b06718e52214
Revises: 475c0ecdf9cd
Create Date: 2020-06-29 09:49:48.341651

"""
import geoalchemy2
from alembic import op

# revision identifiers, used by Alembic.
revision = "b06718e52214"
down_revision = "475c0ecdf9cd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Geometries", schema="pepys") as batch_op:
        batch_op.alter_column(
            "geometry",
            existing_type=geoalchemy2.types.Geometry(),
            type_=geoalchemy2.types.Geometry(srid=4326),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Geometries", schema="pepys") as batch_op:
        batch_op.alter_column(
            "geometry",
            existing_type=geoalchemy2.types.Geometry(srid=4326),
            type_=geoalchemy2.types.Geometry(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
