"""Remove uniqueness of name field of GeometrySubType

Revision ID: 23345c20c2c5
Revises: f331a63ce811
Create Date: 2020-06-15 12:34:54.301497

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "23345c20c2c5"
down_revision = "8b8b16e167cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("GeometrySubTypes", schema="pepys") as batch_op:
        batch_op.drop_constraint("uq_GeometrySubTypes_name", type_="unique")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("GeometrySubTypes", schema="pepys") as batch_op:
        batch_op.create_unique_constraint("uq_GeometrySubTypes_name", ["name"])

    # ### end Alembic commands ###
