"""Add HelpTexts table

Revision ID: 00116b58f22e
Revises: 35f69a534d88
Create Date: 2020-12-01 07:25:11.260187+00:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "00116b58f22e"
down_revision = "35f69a534d88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "HelpTexts",
        sa.Column("help_text_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guidance", sa.String(length=2000), nullable=False),
        sa.PrimaryKeyConstraint("help_text_id", name=op.f("pk_HelpTexts")),
        schema="pepys",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("HelpTexts", schema="pepys")
    # ### end Alembic commands ###
