"""Convert Logs.previous_value to unlimited TEXT data type

Revision ID: ff66e16c21ef
Revises: fb5b94be6485
Create Date: 2021-04-19 08:59:28.781644+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ff66e16c21ef"
down_revision = "fb5b94be6485"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Logs",
        "previous_value",
        existing_type=sa.VARCHAR(length=150),
        type_=sa.Text(),
        existing_nullable=True,
        schema="pepys",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Logs",
        "previous_value",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=150),
        existing_nullable=True,
        schema="pepys",
    )
    # ### end Alembic commands ###
