"""Add stored procedures for Debrief

Revision ID: 1311767a9e56
Revises: d139b551dd55
Create Date: 2021-05-11 09:29:14.589955+00:00

"""
import os

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import sessionmaker

from paths import PEPYS_IMPORT_DIRECTORY

STORED_PROC_PATH = os.path.join(PEPYS_IMPORT_DIRECTORY, "database", "postgres_stored_procedures")

# revision identifiers, used by Alembic.
revision = "1311767a9e56"
down_revision = "d139b551dd55"
branch_labels = None
depends_on = None

Session = sessionmaker()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    stored_procedure_files = [
        os.path.join(STORED_PROC_PATH, "Comments_for.sql"),
        os.path.join(STORED_PROC_PATH, "Contacts_for.sql"),
        os.path.join(STORED_PROC_PATH, "Datafiles_for.sql"),
        os.path.join(STORED_PROC_PATH, "States_for.sql"),
    ]

    for filename in stored_procedure_files:
        with open(filename) as f:
            procedure_definition = f.read()

        session.execute(sa.text(procedure_definition))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute("drop function if exists pepys.Comments_for;")
    session.execute("drop function if exists pepys.Contacts_for;")
    session.execute("drop function if exists pepys.Datafiles_for;")
    session.execute("drop function if exists pepys.States_for;")
    # ### end Alembic commands ###
