"""Extend length of Contact.track_number field

Revision ID: a5a4bc1f7156
Revises: 39b90ad3675e
Create Date: 2021-12-03 16:48:18.324573+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5a4bc1f7156"
down_revision = "39b90ad3675e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Contacts",
        "track_number",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=40),
        existing_nullable=True,
        schema="pepys",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Contacts",
        "track_number",
        existing_type=sa.String(length=40),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
        schema="pepys",
    )
    # ### end Alembic commands ###
