"""Add include_in_timeline field

Revision ID: f17f01e2f2c5
Revises: ff66e16c21ef
Create Date: 2021-04-23 15:04:32.156950+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f17f01e2f2c5"
down_revision = "ff66e16c21ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Serials", sa.Column("include_in_timeline", sa.Boolean()), schema="pepys")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Serials", "include_in_timeline", schema="pepys")
    # ### end Alembic commands ###
