"""Alter Extractions table

Revision ID: 4899e94653f1
Revises: bfb29dfcef94
Create Date: 2021-09-24 12:40:23.320197+00:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4899e94653f1"
down_revision = "c16bbfed85dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Extractions",
        sa.Column("destination_table", sa.String(length=150), nullable=True),
        schema="pepys",
    )
    op.add_column(
        "Extractions",
        sa.Column("entry_id", postgresql.UUID(as_uuid=True), nullable=True),
        schema="pepys",
    )
    op.add_column(
        "Extractions",
        sa.Column("datafile_id", postgresql.UUID(as_uuid=True), nullable=False),
        schema="pepys",
    )
    op.add_column("Extractions", sa.Column("text", sa.Text(), nullable=False), schema="pepys")
    op.add_column(
        "Extractions",
        sa.Column("text_location", sa.String(length=200), nullable=False),
        schema="pepys",
    )
    op.add_column(
        "Extractions", sa.Column("importer", sa.String(length=150), nullable=False), schema="pepys"
    )
    op.add_column(
        "Extractions", sa.Column("interpreted_value", sa.Text(), nullable=False), schema="pepys"
    )
    op.create_foreign_key(
        op.f("fk_Extractions_datafile_id_Datafiles"),
        "Extractions",
        "Datafiles",
        ["datafile_id"],
        ["datafile_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="cascade",
        ondelete="cascade",
    )
    op.drop_column("Extractions", "chars", schema="pepys")
    op.drop_column("Extractions", "table", schema="pepys")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Extractions",
        sa.Column("table", sa.VARCHAR(length=150), autoincrement=False, nullable=False),
        schema="pepys",
    )
    op.add_column(
        "Extractions",
        sa.Column("chars", sa.VARCHAR(length=150), autoincrement=False, nullable=False),
        schema="pepys",
    )
    op.drop_constraint(
        op.f("fk_Extractions_datafile_id_Datafiles"),
        "Extractions",
        schema="pepys",
        type_="foreignkey",
    )
    op.drop_column("Extractions", "interpreted_value", schema="pepys")
    op.drop_column("Extractions", "importer", schema="pepys")
    op.drop_column("Extractions", "text_location", schema="pepys")
    op.drop_column("Extractions", "text", schema="pepys")
    op.drop_column("Extractions", "datafile_id", schema="pepys")
    op.drop_column("Extractions", "entry_id", schema="pepys")
    op.drop_column("Extractions", "destination_table", schema="pepys")
    # ### end Alembic commands ###
