"""Rename new_value to previous_value

Revision ID: 0f8d24a830d0
Revises: 80bc8b0d199b
Create Date: 2021-03-01 10:09:44.140941+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0f8d24a830d0"
down_revision = "80bc8b0d199b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Logs", sa.Column("previous_value", sa.String(length=150), nullable=True), schema="pepys"
    )
    op.drop_column("Logs", "new_value", schema="pepys")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Logs",
        sa.Column("new_value", sa.VARCHAR(length=150), autoincrement=False, nullable=True),
        schema="pepys",
    )
    op.drop_column("Logs", "previous_value", schema="pepys")
    # ### end Alembic commands ###
