"""Extend length of Platform.identifier field

Revision ID: 39b90ad3675e
Revises: 2bc85b76a38b
Create Date: 2021-12-01 21:08:52.761161+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "39b90ad3675e"
down_revision = "2bc85b76a38b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Platforms",
        "identifier",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=50),
        existing_nullable=False,
        schema="pepys",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Platforms",
        "identifier",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
        schema="pepys",
    )
    # ### end Alembic commands ###
