"""Add stored procedures for dashboard

Revision ID: d139b551dd55
Revises: 4d047dd311ef
Create Date: 2021-05-04 15:59:03.925059+00:00

"""
import os

from alembic import op
from sqlalchemy.orm import sessionmaker
from sqlalchemy.sql.expression import text

from paths import PEPYS_IMPORT_DIRECTORY

STORED_PROC_PATH = os.path.join(PEPYS_IMPORT_DIRECTORY, "database", "postgres_stored_procedures")


# revision identifiers, used by Alembic.
revision = "d139b551dd55"
down_revision = "4d047dd311ef"
branch_labels = None
depends_on = None

Session = sessionmaker()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    stored_procedure_files = [
        os.path.join(STORED_PROC_PATH, "dashboard_metadata.sql"),
        os.path.join(STORED_PROC_PATH, "dashboard_stats.sql"),
    ]

    for filename in stored_procedure_files:
        with open(filename) as f:
            procedure_definition = f.read()

        session.execute(text(procedure_definition))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute("drop function if exists pepys.dashboard_stats;")
    session.execute("drop function if exists pepys.dashboard_metadata;")
    # ### end Alembic commands ###
