"""Update dash stored procedures again

Revision ID: c16bbfed85dc
Revises: bfb29dfcef94
Create Date: 2021-09-23 15:28:55.829275+00:00

"""
import os

from alembic import op
from sqlalchemy.orm.session import Session
from sqlalchemy.sql.expression import text

from paths import PEPYS_IMPORT_DIRECTORY

STORED_PROC_PATH = os.path.join(PEPYS_IMPORT_DIRECTORY, "database", "postgres_stored_procedures")


# revision identifiers, used by Alembic.
revision = "c16bbfed85dc"
down_revision = "bfb29dfcef94"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    stored_procedure_files = [
        os.path.join(STORED_PROC_PATH, "dashboard_metadata.sql"),
        os.path.join(STORED_PROC_PATH, "dashboard_stats.sql"),
    ]

    for filename in stored_procedure_files:
        with open(filename) as f:
            procedure_definition = f.read()

        session.execute(text(procedure_definition))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    session.execute("drop function if exists pepys.dashboard_stats;")
    session.execute("drop function if exists pepys.dashboard_metadata;")
    # ### end Alembic commands ###
