"""Add privacy to SerialParticipants

Revision ID: fb5b94be6485
Revises: d33214dcb984
Create Date: 2021-04-17 11:07:27.348366+00:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fb5b94be6485"
down_revision = "d33214dcb984"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "SerialParticipants",
        sa.Column("privacy_id", postgresql.UUID(as_uuid=True), nullable=False),
        schema="pepys",
    )
    op.create_foreign_key(
        op.f("fk_SerialParticipants_privacy_id_Privacies"),
        "SerialParticipants",
        "Privacies",
        ["privacy_id"],
        ["privacy_id"],
        source_schema="pepys",
        referent_schema="pepys",
        onupdate="cascade",
        ondelete="cascade",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_SerialParticipants_privacy_id_Privacies"),
        "SerialParticipants",
        schema="pepys",
        type_="foreignkey",
    )
    op.drop_column("SerialParticipants", "privacy_id", schema="pepys")
    # ### end Alembic commands ###
