"""Make parent_id nullable

Revision ID: 1be821cb7908
Revises: 00116b58f22e
Create Date: 2021-01-21 10:35:10.075259+00:00

"""
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1be821cb7908"
down_revision = "00116b58f22e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Tasks", "parent_id", existing_type=postgresql.UUID(), nullable=True, schema="pepys"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Tasks", "parent_id", existing_type=postgresql.UUID(), nullable=False, schema="pepys"
    )
    # ### end Alembic commands ###
