"""Extend reason field to unlimited length

Revision ID: 2bc85b76a38b
Revises: 40d8ee1342f2
Create Date: 2021-11-10 12:14:51.368498+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2bc85b76a38b"
down_revision = "40d8ee1342f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Changes",
        "reason",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.Text(),
        existing_nullable=False,
        schema="pepys",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Changes",
        "reason",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=500),
        existing_nullable=False,
        schema="pepys",
    )
    # ### end Alembic commands ###
