"""Add indexes

Revision ID: 40d8ee1342f2
Revises: 4899e94653f1
Create Date: 2021-09-29 15:40:44.585519+00:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "40d8ee1342f2"
down_revision = "4899e94653f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_pepys_Activations_end"), "Activations", ["end"], unique=False, schema="pepys"
    )
    op.create_index(
        op.f("ix_pepys_Activations_start"), "Activations", ["start"], unique=False, schema="pepys"
    )
    op.create_index(
        op.f("ix_pepys_Comments_time"), "Comments", ["time"], unique=False, schema="pepys"
    )
    op.create_index(
        op.f("ix_pepys_Contacts_time"), "Contacts", ["time"], unique=False, schema="pepys"
    )
    op.create_index(
        op.f("ix_pepys_Geometries_end"), "Geometries", ["end"], unique=False, schema="pepys"
    )
    op.create_index(
        op.f("ix_pepys_Geometries_start"), "Geometries", ["start"], unique=False, schema="pepys"
    )
    op.create_index(op.f("ix_pepys_Media_time"), "Media", ["time"], unique=False, schema="pepys")
    op.create_index(op.f("ix_pepys_States_time"), "States", ["time"], unique=False, schema="pepys")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pepys_States_time"), table_name="States", schema="pepys")
    op.drop_index(op.f("ix_pepys_Media_time"), table_name="Media", schema="pepys")
    op.drop_index(op.f("ix_pepys_Geometries_start"), table_name="Geometries", schema="pepys")
    op.drop_index(op.f("ix_pepys_Geometries_end"), table_name="Geometries", schema="pepys")
    op.drop_index(op.f("ix_pepys_Contacts_time"), table_name="Contacts", schema="pepys")
    op.drop_index(op.f("ix_pepys_Comments_time"), table_name="Comments", schema="pepys")
    op.drop_index(op.f("ix_pepys_Activations_start"), table_name="Activations", schema="pepys")
    op.drop_index(op.f("ix_pepys_Activations_end"), table_name="Activations", schema="pepys")
    # ### end Alembic commands ###
