"""Add exercise field to Tasks

Revision ID: 004bd2e9fce4
Revises: 13353ad5ffa7
Create Date: 2021-03-26 14:17:47.719015+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "004bd2e9fce4"
down_revision = "45c13d4a9140"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Tasks", sa.Column("exercise", sa.String(length=150), nullable=True), schema="pepys"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Tasks", "exercise", schema="pepys")
    # ### end Alembic commands ###
