"""Alter Extractions table

Revision ID: 06fc100ca166
Revises: bfb29dfcef94
Create Date: 2021-09-16 10:31:52.323630+00:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "06fc100ca166"
down_revision = "bfb29dfcef94"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Extractions",
        sa.Column("entry_id", postgresql.UUID(as_uuid=True), nullable=False),
        schema="pepys",
    )
    op.add_column("Extractions", sa.Column("text", sa.Text(), nullable=False), schema="pepys")
    op.add_column(
        "Extractions",
        sa.Column("text_location", sa.String(length=200), nullable=False),
        schema="pepys",
    )
    op.drop_column("Extractions", "chars", schema="pepys")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Extractions",
        sa.Column("chars", sa.VARCHAR(length=150), autoincrement=False, nullable=False),
        schema="pepys",
    )
    op.drop_column("Extractions", "text_location", schema="pepys")
    op.drop_column("Extractions", "text", schema="pepys")
    op.drop_column("Extractions", "entry_id", schema="pepys")
    # ### end Alembic commands ###
