"""Update nullability of columns of Activations

Revision ID: d5d740c76aa3
Revises: 0f716b0487aa
Create Date: 2020-06-30 14:29:07.829885

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

import pepys_import

# revision identifiers, used by Alembic.
revision = "d5d740c76aa3"
down_revision = "0f716b0487aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Activations", schema=None) as batch_op:
        batch_op.alter_column("end", existing_type=sa.TIMESTAMP(), nullable=True)
        batch_op.alter_column("start", existing_type=sa.TIMESTAMP(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Activations", schema=None) as batch_op:
        batch_op.alter_column("start", existing_type=sa.TIMESTAMP(), nullable=False)
        batch_op.alter_column("end", existing_type=sa.TIMESTAMP(), nullable=False)

    # ### end Alembic commands ###
