"""base2

Revision ID: 7df9dcbd47e7
Revises: bcff0ccb4fbd
Create Date: 2020-04-23 12:26:51.084226

"""
from datetime import datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7df9dcbd47e7"
down_revision = "bcff0ccb4fbd"
branch_labels = None
depends_on = None

meta = sa.MetaData()
geometries = sa.Table(
    "Geometries",
    meta,
    sa.Column("geometry_id", sa.Integer, primary_key=True),
    sa.Column("geometry", sa.NUMERIC()),
    sa.Column("name", sa.String(150), nullable=False),
    sa.Column("geo_type_id", sa.Integer, nullable=False),
    sa.Column("geo_sub_type_id", sa.Integer, nullable=False),
    sa.Column("start", sa.TIMESTAMP),
    sa.Column("end", sa.TIMESTAMP),
    sa.Column("task_id", sa.Integer),
    sa.Column("subject_platform_id", sa.Integer),
    sa.Column("sensor_platform_id", sa.Integer),
    sa.Column("source_id", sa.Integer, nullable=False),
    sa.Column("privacy_id", sa.Integer),
    sa.Column("created_date", sa.DateTime, default=datetime.utcnow),
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Geometries", schema=None, copy_from=geometries) as batch_op:
        batch_op.alter_column("geometry", existing_type=sa.NUMERIC(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Geometries", schema=None, copy_from=geometries) as batch_op:
        batch_op.alter_column("geometry", existing_type=sa.NUMERIC(), nullable=True)

    # ### end Alembic commands ###
