"""base2

Revision ID: 7df9dcbd47e7
Revises: bcff0ccb4fbd
Create Date: 2020-04-23 12:26:51.084226

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7df9dcbd47e7"
down_revision = "bcff0ccb4fbd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Geometries", schema=None) as batch_op:
        batch_op.alter_column("geometry", existing_type=sa.NUMERIC(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Geometries", schema=None) as batch_op:
        batch_op.alter_column("geometry", existing_type=sa.NUMERIC(), nullable=True)

    # ### end Alembic commands ###
