"""Add foreign key for GeomSubType.parent

Revision ID: cd4a4f059f9e
Revises: 07e4b725c547
Create Date: 2020-05-25 11:00:40.867044

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

import pepys_import

# revision identifiers, used by Alembic.
revision = "cd4a4f059f9e"
down_revision = "07e4b725c547"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("GeometrySubTypes", schema=None) as batch_op:
        batch_op.alter_column(
            "parent",
            existing_type=sa.INTEGER(),
            type_=pepys_import.utils.sqlalchemy_utils.UUIDType(length=16),
            existing_nullable=False,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_GeometrySubTypes_parent_GeometryTypes"),
            "GeometryTypes",
            ["parent"],
            ["geo_type_id"],
            onupdate="cascade",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("GeometrySubTypes", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_GeometrySubTypes_parent_GeometryTypes"), type_="foreignkey"
        )
        batch_op.alter_column(
            "parent",
            existing_type=pepys_import.utils.sqlalchemy_utils.UUIDType(length=16),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
