"""Add priority field to Nationality

Revision ID: 480d1f29560f
Revises: 07e4b725c547
Create Date: 2020-05-25 13:17:26.182876

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "480d1f29560f"
down_revision = "cd4a4f059f9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Nationalities", schema=None) as batch_op:
        batch_op.add_column(sa.Column("priority", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Nationalities", schema=None) as batch_op:
        batch_op.drop_column("priority")
    # ### end Alembic commands ###
