"""Add unique constraint for Platform

Revision ID: 4fb1c8780273
Revises: e752bda39400
Create Date: 2020-05-29 16:37:13.344722

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4fb1c8780273"
down_revision = "b03fb305981b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Datafiles", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_Datafile_size_hash", ["size", "hash"])

    with op.batch_alter_table("GeometrySubTypes", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_GeometrySubType_name_parent", ["name", "parent"])
        batch_op.drop_constraint("uq_GeometrySubTypes_name", type_="unique")

    with op.batch_alter_table("Platforms", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_Platform_name_nat_identifier", ["name", "nationality_id", "identifier"]
        )

    with op.batch_alter_table("Sensors", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_sensors_name_host", ["name", "host"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Sensors", schema=None) as batch_op:
        batch_op.drop_constraint("uq_sensors_name_host", type_="unique")

    with op.batch_alter_table("Platforms", schema=None) as batch_op:
        batch_op.drop_constraint("uq_Platform_name_nat_identifier", type_="unique")

    with op.batch_alter_table("GeometrySubTypes", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_GeometrySubTypes_name", ["name"])
        batch_op.drop_constraint("uq_GeometrySubType_name_parent", type_="unique")

    with op.batch_alter_table("Datafiles", schema=None) as batch_op:
        batch_op.drop_constraint("uq_Datafile_size_hash", type_="unique")

    # ### end Alembic commands ###
