"""Add level attribute to Privacies Table

Revision ID: b03fb305981b
Revises: f103f27c4575
Create Date: 2020-06-05 12:43:44.318254

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

import pepys_import

# revision identifiers, used by Alembic.
revision = "b03fb305981b"
down_revision = "f103f27c4575"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Privacies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("level", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Privacies", schema=None) as batch_op:
        batch_op.drop_column("level")
    # ### end Alembic commands ###
