"""Make name nullable for activation and geometry

Revision ID: fd0f7e61611c
Revises: e9f9db37f8f2
Create Date: 2020-06-29 09:51:21.571264

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

import pepys_import

# revision identifiers, used by Alembic.
revision = "fd0f7e61611c"
down_revision = "e9f9db37f8f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Activations", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(length=150), nullable=True)

    with op.batch_alter_table("Geometries", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(length=150), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Geometries", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(length=150), nullable=False)

    with op.batch_alter_table("Activations", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(length=150), nullable=False)

    # ### end Alembic commands ###
