"""Add 3 new indexes

Revision ID: 5858c22ed34c
Revises: 4bdeb14c63b5
Create Date: 2020-12-24 08:55:43.402553+00:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "5858c22ed34c"
down_revision = "4bdeb14c63b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Comments", schema=None) as batch_op:
        batch_op.create_index(
            "idx_comments_comp_platform_source", ["platform_id", "source_id"], unique=False
        )

    with op.batch_alter_table("Contacts", schema=None) as batch_op:
        batch_op.create_index(
            "idx_contacts_comp_sensor_source", ["sensor_id", "source_id"], unique=False
        )

    with op.batch_alter_table("States", schema=None) as batch_op:
        batch_op.create_index(
            "idx_states_comp_sensor_source", ["sensor_id", "source_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("States", schema=None) as batch_op:
        batch_op.drop_index("idx_states_comp_sensor_source")

    with op.batch_alter_table("Contacts", schema=None) as batch_op:
        batch_op.drop_index("idx_contacts_comp_sensor_source")

    with op.batch_alter_table("Comments", schema=None) as batch_op:
        batch_op.drop_index("idx_comments_comp_platform_source")

    # ### end Alembic commands ###
