"""Add HelpTexts table

Revision ID: 4bdeb14c63b5
Revises: 6b92b4b44a5f
Create Date: 2020-12-01 07:24:05.945362+00:00

"""
import sqlalchemy as sa
from alembic import op

import pepys_import

# revision identifiers, used by Alembic.
revision = "4bdeb14c63b5"
down_revision = "6b92b4b44a5f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "HelpTexts",
        sa.Column(
            "help_text_id", pepys_import.utils.sqlalchemy_utils.UUIDType(length=16), nullable=False
        ),
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("guidance", sa.String(length=2000), nullable=False),
        sa.PrimaryKeyConstraint("help_text_id", name=op.f("pk_HelpTexts")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("HelpTexts")
    # ### end Alembic commands ###
