"""Change pennant to identifier and make required

Revision ID: f103f27c4575
Revises: 480d1f29560f
Create Date: 2020-06-03 15:01:57.885447

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

import pepys_import

# revision identifiers, used by Alembic.
revision = "f103f27c4575"
down_revision = "480d1f29560f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Platforms", schema=None) as batch_op:
        batch_op.alter_column(column_name="pennant", new_column_name="identifier", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Platforms", schema=None) as batch_op:
        batch_op.alter_column(column_name="identifier", new_column_name="pennant", nullable=True)
    # ### end Alembic commands ###
