"""Add track number to Contacts table

Revision ID: e9f9db37f8f2
Revises: 806cb8898cab
Create Date: 2020-06-28 12:45:41.897264

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

import pepys_import

# revision identifiers, used by Alembic.
revision = "e9f9db37f8f2"
down_revision = "806cb8898cab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Contacts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("track_number", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Contacts", schema=None) as batch_op:
        batch_op.drop_column("track_number")
    # ### end Alembic commands ###
