"""Add SRID for Geometry field

Revision ID: a18abf8b0488
Revises: fd0f7e61611c
Create Date: 2020-06-29 09:53:29.937222

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

import pepys_import

# revision identifiers, used by Alembic.
revision = "a18abf8b0488"
down_revision = "fd0f7e61611c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Geometries", schema=None) as batch_op:
        batch_op.alter_column(
            "geometry",
            existing_type=sa.NUMERIC(),
            type_=geoalchemy2.types.Geometry(srid=4326, management=True),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Geometries", schema=None) as batch_op:
        batch_op.alter_column(
            "geometry",
            existing_type=geoalchemy2.types.Geometry(srid=4326, management=True),
            type_=sa.NUMERIC(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
