"""Add cascading on delete

Revision ID: 6b92b4b44a5f
Revises: 5a909b3cec9d
Create Date: 2020-11-18 10:37:21.210145+00:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "6b92b4b44a5f"
down_revision = "5a909b3cec9d"
branch_labels = None
depends_on = None


def upgrade():
    # commands auto generated by Alembic - please adjust!
    with op.batch_alter_table("Activations", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_Activations_source_id_Datafiles"),
            "Datafiles",
            ["source_id"],
            ["datafile_id"],
            onupdate="cascade",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("Comments", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_Comments_source_id_Datafiles"),
            "Datafiles",
            ["source_id"],
            ["datafile_id"],
            onupdate="cascade",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("Contacts", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_Contacts_source_id_Datafiles"),
            "Datafiles",
            ["source_id"],
            ["datafile_id"],
            onupdate="cascade",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("Geometries", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_Geometries_source_id_Datafiles"),
            "Datafiles",
            ["source_id"],
            ["datafile_id"],
            onupdate="cascade",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("LogsHoldings", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_LogsHoldings_source_id_Datafiles"),
            "Datafiles",
            ["source_id"],
            ["datafile_id"],
            onupdate="cascade",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("Media", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_Media_source_id_Datafiles"),
            "Datafiles",
            ["source_id"],
            ["datafile_id"],
            onupdate="cascade",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("States", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_States_source_id_Datafiles"),
            "Datafiles",
            ["source_id"],
            ["datafile_id"],
            onupdate="cascade",
            ondelete="CASCADE",
        )

    with op.batch_alter_table("Sensors", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_Sensors_host_Platforms"),
            "Platforms",
            ["host"],
            ["platform_id"],
            onupdate="cascade",
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Activations", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_Activations_source_id_Datafiles",
            "Datafiles",
            ["source_id"],
            ["datafile_id"],
            onupdate="CASCADE",
        )

    with op.batch_alter_table("Comments", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_Comments_source_id_Datafiles",
            "Datafiles",
            ["source_id"],
            ["datafile_id"],
            onupdate="CASCADE",
        )

    with op.batch_alter_table("Contacts", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_Contacts_source_id_Datafiles",
            "Datafiles",
            ["source_id"],
            ["datafile_id"],
            onupdate="CASCADE",
        )

    with op.batch_alter_table("Geometries", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_Geometries_source_id_Datafiles",
            "Datafiles",
            ["source_id"],
            ["datafile_id"],
            onupdate="CASCADE",
        )

    with op.batch_alter_table("LogsHoldings", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_LogsHoldings_source_id_Datafiles",
            "Datafiles",
            ["source_id"],
            ["datafile_id"],
            onupdate="CASCADE",
        )

    with op.batch_alter_table("Media", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_Media_source_id_Datafiles",
            "Datafiles",
            ["source_id"],
            ["datafile_id"],
            onupdate="CASCADE",
        )

    with op.batch_alter_table("States", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_States_source_id_Datafiles",
            "Datafiles",
            ["source_id"],
            ["datafile_id"],
            onupdate="CASCADE",
        )

    with op.batch_alter_table("Sensors", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_Sensors_host_Platforms", "Platforms", ["host"], ["platform_id"], onupdate="CASCADE"
        )
    # ### end Alembic commands ###
