"""Rename reference table cols to name

Revision ID: e752bda39400
Revises: ccc37f794db6
Create Date: 2020-05-18 11:56:26.012057

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e752bda39400"
down_revision = "6c1e62ee267f"
branch_labels = None
depends_on = None


#
# This has been manually edited from the autogenerated script
# as Alembic doesn't pick up column renames properly
# See https://github.com/miguelgrinberg/Flask-Migrate/issues/30


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ClassificationTypes", schema=None) as batch_op:
        batch_op.alter_column(column_name="class_type", new_column_name="name")
        batch_op.create_unique_constraint(batch_op.f("uq_ClassificationTypes_name"), ["name"])
        batch_op.drop_constraint("uq_ClassificationTypes_class_type", type_="unique")

    with op.batch_alter_table("ConfidenceLevels", schema=None) as batch_op:
        batch_op.alter_column(column_name="level", new_column_name="name")
        batch_op.create_unique_constraint(batch_op.f("uq_ConfidenceLevels_name"), ["name"])
        batch_op.drop_constraint("uq_ConfidenceLevels_level", type_="unique")

    with op.batch_alter_table("ContactTypes", schema=None) as batch_op:
        batch_op.alter_column(column_name="contact_type", new_column_name="name")
        batch_op.create_unique_constraint(batch_op.f("uq_ContactTypes_name"), ["name"])
        batch_op.drop_constraint("uq_ContactTypes_contact_type", type_="unique")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("ContactTypes", schema=None) as batch_op:
        batch_op.alter_column(column_name="name", new_column_name="contact_type")
        batch_op.create_unique_constraint("uq_ContactTypes_contact_type", ["contact_type"])
        batch_op.drop_constraint(batch_op.f("uq_ContactTypes_name"), type_="unique")

    with op.batch_alter_table("ConfidenceLevels", schema=None) as batch_op:
        batch_op.alter_column(column_name="name", new_column_name="level")
        batch_op.create_unique_constraint("uq_ConfidenceLevels_level", ["level"])
        batch_op.drop_constraint(batch_op.f("uq_ConfidenceLevels_name"), type_="unique")

    with op.batch_alter_table("ClassificationTypes", schema=None) as batch_op:
        batch_op.alter_column(column_name="name", new_column_name="class_type")
        batch_op.create_unique_constraint("uq_ClassificationTypes_class_type", ["class_type"])
        batch_op.drop_constraint(batch_op.f("uq_ClassificationTypes_name"), type_="unique")

    # ### end Alembic commands ###
