"""Extend length of Platform.identifier field

Revision ID: eb8a93498c02
Revises: cebecb0b77a1
Create Date: 2021-12-01 21:10:36.015159+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eb8a93498c02"
down_revision = "cebecb0b77a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Platforms", schema=None) as batch_op:
        batch_op.alter_column(
            "identifier",
            existing_type=sa.VARCHAR(length=30),
            type_=sa.String(length=50),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Platforms", schema=None) as batch_op:
        batch_op.alter_column(
            "identifier",
            existing_type=sa.String(length=50),
            type_=sa.VARCHAR(length=30),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
