"""Add ConfigOptions table

Revision ID: a7f75ead6204
Revises: a8c6dfa05c6d
Create Date: 2021-05-04 09:42:35.939464+00:00

"""
from datetime import datetime

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import sessionmaker

import pepys_import

# revision identifiers, used by Alembic.
revision = "a7f75ead6204"
down_revision = "a8c6dfa05c6d"
branch_labels = None
depends_on = None


Session = sessionmaker()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ConfigOptions",
        sa.Column(
            "config_option_id",
            pepys_import.utils.sqlalchemy_utils.UUIDType(length=16),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("config_option_id", name=op.f("pk_ConfigOptions")),
        sa.UniqueConstraint("name", name=op.f("uq_ConfigOptions_name")),
    )

    bind = op.get_bind()
    session = Session(bind=bind)

    initial_data = [
        {
            "config_option_id": "9aa691e113ac491fb8d8a886fe434f2a",
            "name": "MessageOfTheDay",
            "description": "Custom message to display in Timeline header",
            "value": "Today's analysis manager is Greta",
            "created_date": datetime.utcnow(),
        },
        {
            "config_option_id": "bc82b46659d94cd99f0d533823a3580a",
            "name": "TimelineRefreshSecs",
            "description": "Interval between Timeline/Dashboard refresh (Secs)",
            "value": "60",
            "created_date": datetime.utcnow(),
        },
    ]

    insert_sql = sa.sql.text(
        "INSERT INTO ConfigOptions (config_option_id, name, description, value, created_date) VALUES (:config_option_id, :name, :description, :value, :created_date);"
    )

    for row_data in initial_data:
        session.execute(insert_sql, row_data)

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ConfigOptions")
    # ### end Alembic commands ###
