"""Extend reason field to unlimited length

Revision ID: cebecb0b77a1
Revises: e5c78b6abb2f
Create Date: 2021-11-10 12:15:56.532772+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cebecb0b77a1"
down_revision = "e5c78b6abb2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Changes", schema=None) as batch_op:
        batch_op.alter_column(
            "reason", existing_type=sa.VARCHAR(length=500), type_=sa.Text(), existing_nullable=False
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Changes", schema=None) as batch_op:
        batch_op.alter_column(
            "reason", existing_type=sa.Text(), type_=sa.VARCHAR(length=500), existing_nullable=False
        )

    # ### end Alembic commands ###
