"""Add uniqueness constraint for Tasks

Revision ID: 1231714189dd
Revises: 2e0e52b59d9e
Create Date: 2021-03-22 10:00:47.325161+00:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "1231714189dd"
down_revision = "2e0e52b59d9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Tasks", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_Task_name_parent_id", ["name", "parent_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Tasks", schema=None) as batch_op:
        batch_op.drop_constraint("uq_Task_name_parent_id", type_="unique")
    # ### end Alembic commands ###
