"""Extend length of Contact.track_number field

Revision ID: fddfa70f811b
Revises: eb8a93498c02
Create Date: 2021-12-03 16:49:33.809704+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fddfa70f811b"
down_revision = "eb8a93498c02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Contacts", schema=None) as batch_op:
        batch_op.alter_column(
            "track_number",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.String(length=40),
            existing_nullable=True,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Contacts", schema=None) as batch_op:
        batch_op.alter_column(
            "track_number",
            existing_type=sa.String(length=40),
            type_=sa.VARCHAR(length=20),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
