"""Alter Extractions table

Revision ID: 3271bbb7a66f
Revises: a7f75ead6204
Create Date: 2021-09-16 10:35:39.039403+00:00

"""
import sqlalchemy as sa
from alembic import op

import pepys_import

# revision identifiers, used by Alembic.
revision = "3271bbb7a66f"
down_revision = "a7f75ead6204"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Extractions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "entry_id", pepys_import.utils.sqlalchemy_utils.UUIDType(length=16), nullable=False
            )
        )
        batch_op.add_column(sa.Column("text", sa.Text(), nullable=False))
        batch_op.add_column(sa.Column("text_location", sa.String(length=200), nullable=False))
        batch_op.drop_column("chars")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Extractions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("chars", sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_column("text_location")
        batch_op.drop_column("text")
        batch_op.drop_column("entry_id")
    # ### end Alembic commands ###
