"""Add exercise field to Tasks

Revision ID: 6754c33dca6d
Revises: 2e0e52b59d9e
Create Date: 2021-03-26 14:19:09.983246+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6754c33dca6d"
down_revision = "1231714189dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("exercise", sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Tasks", schema=None) as batch_op:
        batch_op.drop_column("exercise")
    # ### end Alembic commands ###
