"""Add privacy to SerialParticipants

Revision ID: 2fbdbf54abaf
Revises: 7cd744358c83
Create Date: 2021-04-17 11:08:44.408562+00:00

"""
import sqlalchemy as sa
from alembic import op

import pepys_import

# revision identifiers, used by Alembic.
revision = "2fbdbf54abaf"
down_revision = "7cd744358c83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("SerialParticipants", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "privacy_id",
                pepys_import.utils.sqlalchemy_utils.UUIDType(length=16),
                nullable=False,
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_SerialParticipants_privacy_id_Privacies"),
            "Privacies",
            ["privacy_id"],
            ["privacy_id"],
            onupdate="cascade",
            ondelete="cascade",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("SerialParticipants", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_SerialParticipants_privacy_id_Privacies"), type_="foreignkey"
        )
        batch_op.drop_column("privacy_id")
    # ### end Alembic commands ###
