"""Make parent_id nullable

Revision ID: cb9a5f93f0aa
Revises: 4bdeb14c63b5
Create Date: 2021-01-21 10:30:33.650276+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cb9a5f93f0aa"
down_revision = "4bdeb14c63b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Tasks", schema=None) as batch_op:
        batch_op.alter_column("parent_id", existing_type=sa.CHAR(length=32), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Tasks", schema=None) as batch_op:
        batch_op.alter_column("parent_id", existing_type=sa.CHAR(length=32), nullable=False)

    # ### end Alembic commands ###
