"""Increase identifier

Revision ID: e3a836917a21
Revises: a382a0f4b1be
Create Date: 2021-02-23 09:50:46.619952+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e3a836917a21"
down_revision = "a382a0f4b1be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Platforms", schema=None) as batch_op:
        batch_op.alter_column(
            "identifier",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.String(length=30),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Platforms", schema=None) as batch_op:
        batch_op.alter_column(
            "identifier",
            existing_type=sa.String(length=30),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
