"""Add unique constraint for Serials

Revision ID: a8c6dfa05c6d
Revises: 51e93ee3ed38
Create Date: 2021-04-26 15:49:27.507103+00:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "a8c6dfa05c6d"
down_revision = "51e93ee3ed38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Serials", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_Serial_serial_number_wargame_id", ["serial_number", "wargame_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Serials", schema=None) as batch_op:
        batch_op.drop_constraint("uq_Serial_serial_number_wargame_id", type_="unique")
    # ### end Alembic commands ###
