"""Add include_in_timeline field

Revision ID: 51e93ee3ed38
Revises: 1cdc1050b92f
Create Date: 2021-04-23 15:05:01.944535+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "51e93ee3ed38"
down_revision = "1cdc1050b92f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Serials", schema=None) as batch_op:
        batch_op.add_column(sa.Column("include_in_timeline", sa.Boolean()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Serials", schema=None) as batch_op:
        batch_op.drop_column("include_in_timeline")
    # ### end Alembic commands ###
