name: Test on Linux
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test-pepys:
    name: Test Pepys
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install apt dependencies
        shell: bash -l {0}
        run: |
          sudo apt install -y postgresql-10-postgis-2.5
          sudo apt install -y sqlite3
          sudo apt install -y libgdal-dev libproj-dev libproj-dev
          sudo apt install -y libsqlite3-dev spatialite-bin libsqlite3-mod-spatialite

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
  
      - name: Install pip dependencies
        shell: bash -l {0}
        run: |
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          pip install codecov
  
      - name: Run tests
        shell: bash -l {0}
        run: |
          coverage3 run -m pytest tests
          black --check --diff importers pepys_import pepys_admin
          isort --check-only --diff importers pepys_import pepys_admin
      - name: Get coverage report
        shell: bash -l {0}
        run: coverage3 report
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml